version: '3.5'
services:
  app:
    build: .
    command: rails s -p 3000
    ports:
    - 3000:3000
    volumes:
    - .:/app
    env_file:
      - env/vars.env
    stdin_open: true
    tty: true
    network_mode: "host"
  sidekiq:
    build: .
    command: bundle exec sidekiq -q default -q mailers
    volumes:
    - .:/app 
    env_file:
      - env/vars.env
    stdin_open: true
    tty: true
    network_mode: "host"